#!/bin/sh

tagit
make -C lib $@ &&
make -C asm $@ &&
make -C dis $@ &&
make -C emu $@ ||
exit 1

./asm/build-asm/asm -o test/test.bin test/test.asm
echo $?

./dis/build-dis/dis test/test.bin
echo $?

./emu/build-emu/emu -c 10 test/test.bin
echo $?

#valgrind --leak-check=full -- ./asm/build-asm/asm -o test/test.bin test/test.asm

