
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'X\x8cl\xcd}\x92\xe4\xff\x05\tW\xf7}\xa8a1'
    
_lr_action_items = {'REGISTER':([10,19,22,24,29,],[15,20,25,26,31,]),'STRING':([4,],[14,]),'DIRECTIVE':([0,],[4,]),'INSTRUCTION':([0,],[10,]),',':([15,20,25,],[19,24,29,]),'NUM':([4,10,19,24,29,],[12,16,21,27,32,]),'[':([19,],[22,]),':':([11,],[18,]),']':([25,31,32,],[30,33,34,]),'ID':([0,4,10,19,24,],[11,13,17,23,28,]),'$end':([1,2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,20,21,23,26,27,28,30,33,34,],[-7,-6,-5,-21,-3,0,-2,-8,-1,-24,-22,-23,-18,-19,-20,-4,-16,-15,-17,-12,-13,-14,-9,-11,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instruction_3addr':([0,],[2,]),'directive':([0,],[5,]),'expr':([0,],[6,]),'instruction':([0,],[7,]),'instruction_1addr':([0,],[8,]),'label':([0,],[9,]),'instruction_2addr':([0,],[1,]),'instruction_loadstore':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> label','expr',1,'p_expr','/home/geist/svn/cpu/asmpy/lexparse.py',109),
  ('expr -> instruction','expr',1,'p_expr','/home/geist/svn/cpu/asmpy/lexparse.py',110),
  ('expr -> directive','expr',1,'p_expr','/home/geist/svn/cpu/asmpy/lexparse.py',111),
  ('label -> ID :','label',2,'p_label','/home/geist/svn/cpu/asmpy/lexparse.py',116),
  ('instruction -> instruction_loadstore','instruction',1,'p_instruction','/home/geist/svn/cpu/asmpy/lexparse.py',120),
  ('instruction -> instruction_3addr','instruction',1,'p_instruction','/home/geist/svn/cpu/asmpy/lexparse.py',121),
  ('instruction -> instruction_2addr','instruction',1,'p_instruction','/home/geist/svn/cpu/asmpy/lexparse.py',122),
  ('instruction -> instruction_1addr','instruction',1,'p_instruction','/home/geist/svn/cpu/asmpy/lexparse.py',123),
  ('instruction_loadstore -> INSTRUCTION REGISTER , [ REGISTER ]','instruction_loadstore',6,'p_instruction_loadstore','/home/geist/svn/cpu/asmpy/lexparse.py',126),
  ('instruction_loadstore -> INSTRUCTION REGISTER , [ REGISTER , NUM ]','instruction_loadstore',8,'p_instruction_loadstore','/home/geist/svn/cpu/asmpy/lexparse.py',127),
  ('instruction_loadstore -> INSTRUCTION REGISTER , [ REGISTER , REGISTER ]','instruction_loadstore',8,'p_instruction_loadstore','/home/geist/svn/cpu/asmpy/lexparse.py',128),
  ('instruction_3addr -> INSTRUCTION REGISTER , REGISTER , REGISTER','instruction_3addr',6,'p_instruction_3addr','/home/geist/svn/cpu/asmpy/lexparse.py',133),
  ('instruction_3addr -> INSTRUCTION REGISTER , REGISTER , NUM','instruction_3addr',6,'p_instruction_3addr','/home/geist/svn/cpu/asmpy/lexparse.py',134),
  ('instruction_3addr -> INSTRUCTION REGISTER , REGISTER , ID','instruction_3addr',6,'p_instruction_3addr','/home/geist/svn/cpu/asmpy/lexparse.py',135),
  ('instruction_2addr -> INSTRUCTION REGISTER , NUM','instruction_2addr',4,'p_instruction_2addr','/home/geist/svn/cpu/asmpy/lexparse.py',139),
  ('instruction_2addr -> INSTRUCTION REGISTER , REGISTER','instruction_2addr',4,'p_instruction_2addr','/home/geist/svn/cpu/asmpy/lexparse.py',140),
  ('instruction_2addr -> INSTRUCTION REGISTER , ID','instruction_2addr',4,'p_instruction_2addr','/home/geist/svn/cpu/asmpy/lexparse.py',141),
  ('instruction_1addr -> INSTRUCTION REGISTER','instruction_1addr',2,'p_instruction_1addr','/home/geist/svn/cpu/asmpy/lexparse.py',145),
  ('instruction_1addr -> INSTRUCTION NUM','instruction_1addr',2,'p_instruction_1addr','/home/geist/svn/cpu/asmpy/lexparse.py',146),
  ('instruction_1addr -> INSTRUCTION ID','instruction_1addr',2,'p_instruction_1addr','/home/geist/svn/cpu/asmpy/lexparse.py',147),
  ('directive -> DIRECTIVE','directive',1,'p_directive','/home/geist/svn/cpu/asmpy/lexparse.py',151),
  ('directive -> DIRECTIVE ID','directive',2,'p_directive','/home/geist/svn/cpu/asmpy/lexparse.py',152),
  ('directive -> DIRECTIVE STRING','directive',2,'p_directive','/home/geist/svn/cpu/asmpy/lexparse.py',153),
  ('directive -> DIRECTIVE NUM','directive',2,'p_directive','/home/geist/svn/cpu/asmpy/lexparse.py',154),
]
